export const step2TestData: Record<string, unknown> = {
  matriculaMagistrado: 'M-1234567',
  nomeMagistrado: 'Juiz de Direito Teste',
  matriculaGerenteSecretaria: 'S-7654321',
  nomeGerenteSecretaria: 'Gerente da Secretaria Teste',
  codigoVaraRequisicao: '100240413',
  nomeVaraRequisicao: '2ª Vara Cível da Comarca de São Paulo',
  numeroUnicoCnj: '1234567-89.2023.8.13.0024',
  numeroProcessoOriginario: '0000000-00.0000.0.00.0000',
  houveProcessoConhecimento: 'Sim',
  dataAjuizamentoConhecimento: '2020-01-15',
  dataCitacaoConhecimento: '2020-02-10',
  tipoTransitoJulgado: 'Sentença',
  dataTransitoJulgadoSentenca: '2022-05-20',
  houveEmbargosExecucao: 'Não',
  dataDecursoPrazoEmbargos: '2023-01-10',
  naturezaCredito: 'Alimentar',
  dataIntimacaoPartes: '2023-06-01',
  tipoRequisicao: 'Original',
  possuiNaturezaSalarial: 'Sim',
  condicaoServidor: 'Ativo',
  orgaoVinculacaoServidor: 'Secretaria de Educação',
  codigoAssuntoProcesso: '3371',
  descricaoAssuntoProcesso: 'Homicídio Simples',
  tipoBeneficiarioRequisicao: 'Beneficiário Principal',
  possuiDestaqueHonorarios: 'Sim',
  houveCessaoCreditoPrincipal: 'Não',
  houveSucessaoCreditoPrincipal: 'Não',
  tipoCessaoCreditoPrincipal: 'Total',
  houveCessaoHonorariosContratuais: 'Não',
  houvePenhoraHonorariosContratuais: 'Não',
  houveSucessaoHonorariosContratuais: 'Não',
  entidadeDevedora: 'ESTADO DE MINAS GERAIS',
  cnpjEntidadeDevedora: '18.715.615/0001-60'
};