export const step3TestData: Record<string, unknown> = {
  tipoBeneficiarioRequisicao: 'Beneficiário Principal',
  idBeneficiarioSelecionado: '1',
  nomeBeneficiario: 'João da Silva',
  nomeSocialBeneficiario: '',
  dataNascimentoBeneficiario: '1980-05-15',
  idadeBeneficiario: 45,
  tipoDocumentoBeneficiario: 'CPF',
  numeroDocumentoBeneficiario: '111.222.333-44',
  numeroInscricaoSocial: '12345678901',
  possuiDoencaGrave: 'Não',
  possuiDeficiencia: 'Não',
  possuiCreditoPreferencial: 'Não',
  condicaoCapacidadeBeneficiario: 'NaoSeAplica',
  titularContaBancaria: 'BeneficiarioCredito',
  tipoDocumentoTitularBancario: 'CPF',
  cpfTitularBancario: '111.222.333-44',
  codigoBancoTitular: '001',
  tipoContaBancariaTitular: 'Corrente',
  agenciaBancariaTitular: '12345',
  numeroContaBancariaTitular: '987654321',
  listaProcuradoresAdicionados: [
    {
      id: 'mock-proc-1',
      nome: 'Dr. Roberto Alves',
      documento: 'CPF - 123.456.789-00',
      oab: '12345',
      categoria: 'A',
      secao: 'SP',
      rawData: { tipoDoc: 'CPF', docCpf: '123.456.789-00', docCnpj: '', docRne: '' }
    }
  ],
  possuiDadosBancariosProcurador: 'Não',
  valorPrincipalCorrigido: 'R$ 150.000,00',
  dataLiquidacaoCalculo: '2023-10-01',
  possuiJurosMoratorios: 'Sim',
  valorJurosMoratorios: 'R$ 15.000,00',
  possuiJurosCompensatorios: 'Não',
  possuiCustasDespesasMulta: 'Não',
  possuiDescontoPrevidenciario: 'Sim',
  valorDescontoPrevidenciario: 'R$ 5.000,00',
  tipoRegimePrevidenciario: 'GeralINSS',
  possuiIncidenciaItcd: 'Não',
  possuiTributacaoRra: 'Sim',
  dataInicialTributacaoRra: '2020-01-01',
  dataFinalTributacaoRra: '2022-12-31',
  quantidadeParcelasDecimoTerceiroRra: 3,
  quantidadeMesesTributacaoRra: 36,
  valorBrutoTotal: 'R$ 165.000,00'
};
