export const FIELD_LABELS: Record<string, string> = {
  numeroProcesso: 'Número do Processo',
  instanciaJustica: 'Instância',
  matriculaMagistrado: 'Matrícula do Magistrado',
  nomeMagistrado: 'Nome do Magistrado',
  matriculaGerenteSecretaria: 'Matrícula do Gerente da Secretaria',
  nomeGerenteSecretaria: 'Nome do Gerente da Secretaria',
  codigoVaraRequisicao: 'Código da Vara',
  nomeVaraRequisicao: 'Nome da Vara',
  numeroUnicoCnj: 'Numeração Única (CNJ)',
  numeroProcessoOriginario: 'Número Originário Anterior',
  houveProcessoConhecimento: 'Houve Processo de Conhecimento?',
  dataAjuizamentoConhecimento: 'Data de Ajuizamento (Conhecimento)',
  dataCitacaoConhecimento: 'Data da Citação (Conhecimento)',
  tipoTransitoJulgado: 'Tipo do Trânsito em Julgado',
  dataTransitoJulgadoSentenca: 'Data do Trânsito (Sentença)',
  dataTransitoJulgadoAcordao: 'Data do Trânsito (Acórdão)',
  houveEmbargosExecucao: 'Houve Embargos à Execução?',
  dataTransitoJulgadoEmbargos: 'Data do Trânsito (Embargos)',
  dataDecursoPrazoEmbargos: 'Data do Decurso de Prazo (Embargos)',
  naturezaCredito: 'Natureza do Crédito',
  dataIntimacaoPartes: 'Data da Intimação das Partes',
  tipoRequisicao: 'Tipo de Requisição',
  dataReconhecimentoParcela: 'Data do Reconhecimento da Parcela',
  possuiNaturezaSalarial: 'Ação de Natureza Salarial?',
  condicaoServidor: 'Condição do Servidor',
  orgaoVinculacaoServidor: 'Órgão de Vinculação',
  codigoAssuntoProcesso: 'Código do Assunto',
  descricaoAssuntoProcesso: 'Descrição do Assunto',
  tipoBeneficiarioRequisicao: 'Tipo de Beneficiário',
  possuiDestaqueHonorarios: 'Previsão de Destaque de Honorários?',
  houveCessaoCreditoPrincipal: 'Cessão do Crédito Principal?',
  houveSucessaoCreditoPrincipal: 'Sucessão do Crédito Principal?',
  tipoCessaoCreditoPrincipal: 'Tipo de Cessão',
  houvePenhoraCreditoPrincipal: 'Penhora do Crédito Principal?',
  nomeBeneficiarioOriginario: 'Nome do Beneficiário Originário',
  tipoDocumentoBeneficiarioOriginario: 'Tipo de Documento (Originário)',
  cpfBeneficiarioOriginario: 'CPF (Originário)',
  cnpjBeneficiarioOriginario: 'CNPJ (Originário)',
  rneBeneficiarioOriginario: 'RNE (Originário)',
  houveCessaoHonorariosContratuais: 'Cessão de Honorários Contratuais?',
  houvePenhoraHonorariosContratuais: 'Penhora de Honorários Contratuais?',
  houveSucessaoHonorariosContratuais: 'Sucessão de Honorários Contratuais?',
  nomeBeneficiarioOriginarioHonorarios: 'Nome (Originário Honorários)',
  tipoDocumentoBeneficiarioOriginarioHonorarios: 'Tipo Doc. (Originário Honorários)',
  cpfBeneficiarioOriginarioHonorarios: 'CPF (Originário Honorários)',
  cnpjBeneficiarioOriginarioHonorarios: 'CNPJ (Originário Honorários)',
  rneBeneficiarioOriginarioHonorarios: 'RNE (Originário Honorários)',
  houveCessaoHonorariosSucumbenciais: 'Cessão de Honorários Sucumbenciais?',
  houvePenhoraHonorariosSucumbenciais: 'Penhora de Honorários Sucumbenciais?',
  houveSucessaoHonorariosSucumbenciais: 'Sucessão de Honorários Sucumbenciais?',
  houveCessaoHonorariosPericiais: 'Cessão de Honorários Periciais?',
  houvePenhoraHonorariosPericiais: 'Penhora de Honorários Periciais?',
  houveSucessaoHonorariosPericiais: 'Sucessão de Honorários Periciais?',
  entidadeDevedora: 'Entidade Devedora',
  cnpjEntidadeDevedora: 'CNPJ da Entidade Devedora',
  idBeneficiarioSelecionado: 'ID Beneficiário',
  nomeBeneficiario: 'Nome do Beneficiário',
  nomeSocialBeneficiario: 'Nome Social',
  dataNascimentoBeneficiario: 'Data de Nascimento',
  idadeBeneficiario: 'Idade',
  tipoDocumentoBeneficiario: 'Tipo de Documento',
  numeroDocumentoBeneficiario: 'Número do Documento',
  numeroInscricaoSocial: 'Nº PIX/PASEP/NIT',
  possuiDoencaGrave: 'Doença Grave?',
  possuiDeficiencia: 'Pessoa com Deficiência?',
  possuiCreditoPreferencial: 'Crédito Preferencial?',
  condicaoCapacidadeBeneficiario: 'Capacidade do Beneficiário',
  nomeRepresentanteLegal: 'Nome do Representante Legal',
  tipoDocumentoRepresentanteLegal: 'Tipo Doc. (Representante Legal)',
  documentoRepresentanteLegalPlaceholder: 'Doc. (Representante Legal)',
  cpfRepresentanteLegal: 'CPF (Representante Legal)',
  cnpjRepresentanteLegal: 'CNPJ (Representante Legal)',
  rneRepresentanteLegal: 'RNE (Representante Legal)',
  numeroOabRepresentanteLegal: 'OAB (Representante Legal)',
  categoriaOabRepresentanteLegal: 'Categoria OAB (Representante Legal)',
  secaoOabRepresentanteLegal: 'Seção OAB (Representante Legal)',
  titularContaBancaria: 'Titular da Conta Bancária',
  tipoDocumentoTitularBancario: 'Tipo Doc. (Titular Conta)',
  documentoTitularBancarioPlaceholder: 'Doc. (Titular Conta)',
  cpfTitularBancario: 'CPF (Titular Conta)',
  cnpjTitularBancario: 'CNPJ (Titular Conta)',
  rneTitularBancario: 'RNE (Titular Conta)',
  codigoBancoTitular: 'Código do Banco (Titular)',
  tipoContaBancariaTitular: 'Tipo de Conta',
  agenciaBancariaTitular: 'Agência',
  numeroContaBancariaTitular: 'Número da Conta',
  idProcuradorSelecionado: 'ID Procurador',
  nomeProcurador: 'Nome do Procurador',
  tipoDocumentoProcurador: 'Tipo Doc. (Procurador)',
  documentoProcuradorPlaceholder: 'Doc. (Procurador)',
  cpfProcurador: 'CPF (Procurador)',
  cnpjProcurador: 'CNPJ (Procurador)',
  rneProcurador: 'RNE (Procurador)',
  numeroOabProcurador: 'OAB (Procurador)',
  categoriaOabProcurador: 'Categoria OAB (Procurador)',
  secaoOabProcurador: 'Seção OAB (Procurador)',
  possuiDadosBancariosProcurador: 'Dados Bancários do Procurador?',
  titularContaBancariaProcurador: 'Titular da Conta (Procurador)',
  nomeTitularBancarioProcurador: 'Nome Titular (Procurador)',
  tipoDocumentoTitularBancarioProcurador: 'Tipo Doc. Titular (Procurador)',
  documentoTitularBancarioProcuradorPlaceholder: 'Doc. Titular (Procurador)',
  cpfTitularBancarioProcurador: 'CPF Titular (Procurador)',
  cnpjTitularBancarioProcurador: 'CNPJ Titular (Procurador)',
  rneTitularBancarioProcurador: 'RNE Titular (Procurador)',
  codigoBancoProcurador: 'Banco do Procurador',
  tipoContaBancariaProcurador: 'Tipo Conta (Procurador)',
  agenciaBancariaProcurador: 'Agência (Procurador)',
  numeroContaBancariaProcurador: 'Nº Conta (Procurador)',
  valorPrincipalCorrigido: 'Valor Principal Corrigido',
  dataLiquidacaoCalculo: 'Data de Liquidação',
  possuiJurosMoratorios: 'Há Juros Moratórios?',
  valorJurosMoratorios: 'Valor dos Juros Moratórios',
  possuiJurosCompensatorios: 'Há Juros Compensatórios?',
  valorJurosCompensatorios: 'Valor dos Juros Compensatórios',
  possuiCustasDespesasMulta: 'Há Custas/Despesas/Multa?',
  valorCustasDespesasMulta: 'Valor das Custas/Despesas/Multa',
  possuiDescontoPrevidenciario: 'Há Desconto Previdenciário?',
  valorDescontoPrevidenciario: 'Valor do Desconto Previdenciário',
  tipoRegimePrevidenciario: 'Regime Previdenciário',
  nomeOrgaoPrevidenciario: 'Nome do Órgão Previdenciário',
  cnpjOrgaoPrevidenciario: 'CNPJ do Órgão Previdenciário',
  possuiDadosBancariosOrgaoPrevidenciario: 'Dados Bancários do Órgão?',
  codigoBancoOrgaoPrevidenciario: 'Banco do Órgão Previdenciário',
  tipoContaBancariaOrgaoPrevidenciario: 'Tipo Conta do Órgão',
  agenciaBancariaOrgaoPrevidenciario: 'Agência do Órgão',
  numeroContaBancariaOrgaoPrevidenciario: 'Nº Conta do Órgão',
  valorAssistenciaMedica: 'Valor Assistência Médica',
  valorFundoAposentadoria: 'Valor Fundo de Aposentadoria',
  possuiIncidenciaItcd: 'Há Incidência ITCD?',
  percentualAliquotaItcd: 'Alíquota ITCD (%)',
  possuiTributacaoRra: 'Há Tributação RRA?',
  dataInicialTributacaoRra: 'Data Inicial (RRA)',
  dataFinalTributacaoRra: 'Data Final (RRA)',
  quantidadeParcelasDecimoTerceiroRra: 'Qtd. Parcelas 13º (RRA)',
  quantidadeMesesTributacaoRra: 'Qtd. Meses (RRA)',
  valorBrutoTotal: 'Valor Bruto Total'
};